word_list = [
'Fernando Alonso',
'Sebastian Vettel',
'Lewis Hamilton',
'Ayrton Senna',
'Michael Schumacher',
'Nelson Piquet',
'Jack Brabham',
'Phil Hill',
'Graham Hill',
'Damon Hill',
'Jody Scheckter',
'Keke Rosberg',
'Nico Rosberg',
'Jenson Button',
'Mika Hakkinnen',
'Kimi Raikonnen',
'Jackie Stewart',
'Jochen Rindt',
'Alain Prost',
'Juan Manuel Fangio',
'Nigel Mansell',
'Jim Clark',
'Alan Jones',
'Mario Andretti',
'Denny Hulme',
'Mike Hawthorn',
'Emerson Fittipaldi',
'Nino Farina',
'Alberto Ascari',
'James Hunt',
'Niki Lauda',
'Jacques Villeneuve',
'John Surtees',
'Brabham',
'Ferrari',
'Red Bull',
'Mclaren',
'Mercedes',
'Brawn',
'Aston Martin',
'Lotus',
'Williams',
'Renault',
'Tyrrell',
'Haas',
'AlphaTauri',
'Alfa Romeo',
'Alpine',
]